receivers:
  tracemock:  
    interval: 1m
    number_of_traces: 1
  otlp:
    protocols:
      grpc:
        endpoint: localhost:55680

processors:

exporters:
  logging:
    logLevel: debug
  jaeger:
    endpoint: localhost:14250
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp, tracemock]
      processors: []
      exporters: [jaeger, logging]